/**
 * @file rover.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Fri Jul 31 17:57:25 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ROVER_H
#define ROVER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ROVER_REFERENCE_FRAME_ID (0x0au)
#define ROVER_ENCODER_RPMS_FRAME_ID (0x0bu)
#define ROVER_IMU_GYRO_XY_FRAME_ID (0x0cu)
#define ROVER_IMU_ACCEL_XY_FRAME_ID (0x0du)
#define ROVER_IMU_Z_FRAME_ID (0x0eu)

/* Frame lengths in bytes. */
#define ROVER_REFERENCE_LENGTH (8u)
#define ROVER_ENCODER_RPMS_LENGTH (8u)
#define ROVER_IMU_GYRO_XY_LENGTH (8u)
#define ROVER_IMU_ACCEL_XY_LENGTH (8u)
#define ROVER_IMU_Z_LENGTH (8u)

/* Extended or standard frame types. */
#define ROVER_REFERENCE_IS_EXTENDED (0)
#define ROVER_ENCODER_RPMS_IS_EXTENDED (0)
#define ROVER_IMU_GYRO_XY_IS_EXTENDED (0)
#define ROVER_IMU_ACCEL_XY_IS_EXTENDED (0)
#define ROVER_IMU_Z_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define ROVER_REFERENCE_NAME "Reference"
#define ROVER_ENCODER_RPMS_NAME "EncoderRpms"
#define ROVER_IMU_GYRO_XY_NAME "ImuGyroXy"
#define ROVER_IMU_ACCEL_XY_NAME "ImuAccelXy"
#define ROVER_IMU_Z_NAME "ImuZ"

/* Signal Names. */
#define ROVER_REFERENCE_FRONT_LEFT_NAME "FrontLeft"
#define ROVER_REFERENCE_REAR_LEFT_NAME "RearLeft"
#define ROVER_REFERENCE_FRONT_RIGHT_NAME "FrontRight"
#define ROVER_REFERENCE_REAR_RIGHT_NAME "RearRight"
#define ROVER_ENCODER_RPMS_FRONT_LEFT_NAME "FrontLeft"
#define ROVER_ENCODER_RPMS_REAR_LEFT_NAME "RearLeft"
#define ROVER_ENCODER_RPMS_FRONT_RIGHT_NAME "FrontRight"
#define ROVER_ENCODER_RPMS_REAR_RIGHT_NAME "RearRight"
#define ROVER_IMU_GYRO_XY_GYRO_X_NAME "GyroX"
#define ROVER_IMU_GYRO_XY_GYRO_Y_NAME "GyroY"
#define ROVER_IMU_ACCEL_XY_ACCEL_X_NAME "AccelX"
#define ROVER_IMU_ACCEL_XY_ACCEL_Y_NAME "AccelY"
#define ROVER_IMU_Z_GYRO_Z_NAME "GyroZ"
#define ROVER_IMU_Z_ACCEL_Z_NAME "AccelZ"

/**
 * Signals in message Reference.
 *
 * All signal values are as on the CAN bus.
 */
struct rover_reference_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t front_left;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t rear_left;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t front_right;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t rear_right;
};

/**
 * Signals in message EncoderRpms.
 *
 * Raw encoder RPMs. Physical RPM = raw_value * (1/182).
 *
 * All signal values are as on the CAN bus.
 */
struct rover_encoder_rpms_t {
    /**
     * Range: -180..180 (-180..180 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t front_left;

    /**
     * Range: -180..180 (-180..180 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t rear_left;

    /**
     * Range: -180..180 (-180..180 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t front_right;

    /**
     * Range: -180..180 (-180..180 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t rear_right;
};

/**
 * Signals in message ImuGyroXy.
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_gyro_xy_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t gyro_x;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t gyro_y;
};

/**
 * Signals in message ImuAccelXy.
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_accel_xy_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t accel_x;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t accel_y;
};

/**
 * Signals in message ImuZ.
 *
 * All signal values are as on the CAN bus.
 */
struct rover_imu_z_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t gyro_z;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t accel_z;
};

/**
 * Pack message Reference.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_reference_pack(
    uint8_t *dst_p,
    const struct rover_reference_t *src_p,
    size_t size);

/**
 * Unpack message Reference.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_reference_unpack(
    struct rover_reference_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Reference.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_reference_init(struct rover_reference_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_reference_front_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_reference_front_left_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_front_left_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_front_left_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_reference_rear_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_reference_rear_left_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_rear_left_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_rear_left_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_reference_front_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_reference_front_right_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_front_right_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_front_right_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_reference_rear_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_reference_rear_right_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_rear_right_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_reference_rear_right_is_in_phys_range(double value);

/**
 * Pack message EncoderRpms.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_encoder_rpms_pack(
    uint8_t *dst_p,
    const struct rover_encoder_rpms_t *src_p,
    size_t size);

/**
 * Unpack message EncoderRpms.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_encoder_rpms_unpack(
    struct rover_encoder_rpms_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EncoderRpms.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_encoder_rpms_init(struct rover_encoder_rpms_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_encoder_rpms_front_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_encoder_rpms_front_left_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_front_left_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_front_left_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_encoder_rpms_rear_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_encoder_rpms_rear_left_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_rear_left_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_rear_left_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_encoder_rpms_front_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_encoder_rpms_front_right_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_front_right_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_front_right_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t rover_encoder_rpms_rear_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_encoder_rpms_rear_right_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_rear_right_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_encoder_rpms_rear_right_is_in_phys_range(double value);

/**
 * Pack message ImuGyroXy.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_gyro_xy_pack(
    uint8_t *dst_p,
    const struct rover_imu_gyro_xy_t *src_p,
    size_t size);

/**
 * Unpack message ImuGyroXy.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_gyro_xy_unpack(
    struct rover_imu_gyro_xy_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuGyroXy.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_gyro_xy_init(struct rover_imu_gyro_xy_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_gyro_xy_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_xy_gyro_x_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_xy_gyro_x_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_xy_gyro_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_gyro_xy_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_gyro_xy_gyro_y_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_xy_gyro_y_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_gyro_xy_gyro_y_is_in_phys_range(double value);

/**
 * Pack message ImuAccelXy.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_accel_xy_pack(
    uint8_t *dst_p,
    const struct rover_imu_accel_xy_t *src_p,
    size_t size);

/**
 * Unpack message ImuAccelXy.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_accel_xy_unpack(
    struct rover_imu_accel_xy_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuAccelXy.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_accel_xy_init(struct rover_imu_accel_xy_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_accel_xy_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_xy_accel_x_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_xy_accel_x_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_xy_accel_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_accel_xy_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_accel_xy_accel_y_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_xy_accel_y_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_accel_xy_accel_y_is_in_phys_range(double value);

/**
 * Pack message ImuZ.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int rover_imu_z_pack(
    uint8_t *dst_p,
    const struct rover_imu_z_t *src_p,
    size_t size);

/**
 * Unpack message ImuZ.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int rover_imu_z_unpack(
    struct rover_imu_z_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuZ.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int rover_imu_z_init(struct rover_imu_z_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_z_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_z_gyro_z_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_z_gyro_z_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_z_gyro_z_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t rover_imu_z_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double rover_imu_z_accel_z_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_z_accel_z_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool rover_imu_z_accel_z_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
