/**
 * @file rover.c
 *
 * @brief This source file was generated by cantools version 42.0.3 Fri Jul 31 17:57:25 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "mivia_rover_platform/rover.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int rover_reference_pack(
    uint8_t *dst_p,
    const struct rover_reference_t *src_p,
    size_t size)
{
    uint16_t front_left;
    uint16_t front_right;
    uint16_t rear_left;
    uint16_t rear_right;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    front_left = (uint16_t)src_p->front_left;
    dst_p[0] |= pack_left_shift_u16(front_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(front_left, 8u, 0xffu);
    rear_left = (uint16_t)src_p->rear_left;
    dst_p[2] |= pack_left_shift_u16(rear_left, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rear_left, 8u, 0xffu);
    front_right = (uint16_t)src_p->front_right;
    dst_p[4] |= pack_left_shift_u16(front_right, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(front_right, 8u, 0xffu);
    rear_right = (uint16_t)src_p->rear_right;
    dst_p[6] |= pack_left_shift_u16(rear_right, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rear_right, 8u, 0xffu);

    return (8);
}

int rover_reference_unpack(
    struct rover_reference_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_left;
    uint16_t front_right;
    uint16_t rear_left;
    uint16_t rear_right;

    if (size < 8u) {
        return (-EINVAL);
    }

    front_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    front_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->front_left = (int16_t)front_left;
    rear_left = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rear_left |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rear_left = (int16_t)rear_left;
    front_right = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    front_right |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->front_right = (int16_t)front_right;
    rear_right = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rear_right |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rear_right = (int16_t)rear_right;

    return (0);
}

int rover_reference_init(struct rover_reference_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_reference_t));

    return 0;
}

int16_t rover_reference_front_left_encode(double value)
{
    return (int16_t)(value);
}

double rover_reference_front_left_decode(int16_t value)
{
    return ((double)value);
}

bool rover_reference_front_left_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool rover_reference_front_left_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int16_t rover_reference_rear_left_encode(double value)
{
    return (int16_t)(value);
}

double rover_reference_rear_left_decode(int16_t value)
{
    return ((double)value);
}

bool rover_reference_rear_left_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool rover_reference_rear_left_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int16_t rover_reference_front_right_encode(double value)
{
    return (int16_t)(value);
}

double rover_reference_front_right_decode(int16_t value)
{
    return ((double)value);
}

bool rover_reference_front_right_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool rover_reference_front_right_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int16_t rover_reference_rear_right_encode(double value)
{
    return (int16_t)(value);
}

double rover_reference_rear_right_decode(int16_t value)
{
    return ((double)value);
}

bool rover_reference_rear_right_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool rover_reference_rear_right_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int rover_encoder_rpms_pack(
    uint8_t *dst_p,
    const struct rover_encoder_rpms_t *src_p,
    size_t size)
{
    uint16_t front_left;
    uint16_t front_right;
    uint16_t rear_left;
    uint16_t rear_right;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    front_left = (uint16_t)src_p->front_left;
    dst_p[0] |= pack_left_shift_u16(front_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(front_left, 8u, 0xffu);
    rear_left = (uint16_t)src_p->rear_left;
    dst_p[2] |= pack_left_shift_u16(rear_left, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rear_left, 8u, 0xffu);
    front_right = (uint16_t)src_p->front_right;
    dst_p[4] |= pack_left_shift_u16(front_right, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(front_right, 8u, 0xffu);
    rear_right = (uint16_t)src_p->rear_right;
    dst_p[6] |= pack_left_shift_u16(rear_right, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rear_right, 8u, 0xffu);

    return (8);
}

int rover_encoder_rpms_unpack(
    struct rover_encoder_rpms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_left;
    uint16_t front_right;
    uint16_t rear_left;
    uint16_t rear_right;

    if (size < 8u) {
        return (-EINVAL);
    }

    front_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    front_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->front_left = (int16_t)front_left;
    rear_left = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rear_left |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rear_left = (int16_t)rear_left;
    front_right = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    front_right |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->front_right = (int16_t)front_right;
    rear_right = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rear_right |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rear_right = (int16_t)rear_right;

    return (0);
}

int rover_encoder_rpms_init(struct rover_encoder_rpms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_encoder_rpms_t));

    return 0;
}

int16_t rover_encoder_rpms_front_left_encode(double value)
{
    return (int16_t)(value);
}

double rover_encoder_rpms_front_left_decode(int16_t value)
{
    return ((double)value);
}

bool rover_encoder_rpms_front_left_is_in_range(int16_t value)
{
    return ((value >= -180) && (value <= 180));
}

bool rover_encoder_rpms_front_left_is_in_phys_range(double value)
{
    return ((value >= -180.0) && (value <= 180.0));
}

int16_t rover_encoder_rpms_rear_left_encode(double value)
{
    return (int16_t)(value);
}

double rover_encoder_rpms_rear_left_decode(int16_t value)
{
    return ((double)value);
}

bool rover_encoder_rpms_rear_left_is_in_range(int16_t value)
{
    return ((value >= -180) && (value <= 180));
}

bool rover_encoder_rpms_rear_left_is_in_phys_range(double value)
{
    return ((value >= -180.0) && (value <= 180.0));
}

int16_t rover_encoder_rpms_front_right_encode(double value)
{
    return (int16_t)(value);
}

double rover_encoder_rpms_front_right_decode(int16_t value)
{
    return ((double)value);
}

bool rover_encoder_rpms_front_right_is_in_range(int16_t value)
{
    return ((value >= -180) && (value <= 180));
}

bool rover_encoder_rpms_front_right_is_in_phys_range(double value)
{
    return ((value >= -180.0) && (value <= 180.0));
}

int16_t rover_encoder_rpms_rear_right_encode(double value)
{
    return (int16_t)(value);
}

double rover_encoder_rpms_rear_right_decode(int16_t value)
{
    return ((double)value);
}

bool rover_encoder_rpms_rear_right_is_in_range(int16_t value)
{
    return ((value >= -180) && (value <= 180));
}

bool rover_encoder_rpms_rear_right_is_in_phys_range(double value)
{
    return ((value >= -180.0) && (value <= 180.0));
}

int rover_imu_gyro_xy_pack(
    uint8_t *dst_p,
    const struct rover_imu_gyro_xy_t *src_p,
    size_t size)
{
    uint32_t gyro_x;
    uint32_t gyro_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gyro_x = (uint32_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u32(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gyro_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(gyro_x, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(gyro_x, 24u, 0xffu);
    gyro_y = (uint32_t)src_p->gyro_y;
    dst_p[4] |= pack_left_shift_u32(gyro_y, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(gyro_y, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(gyro_y, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(gyro_y, 24u, 0xffu);

    return (8);
}

int rover_imu_gyro_xy_unpack(
    struct rover_imu_gyro_xy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t gyro_x;
    uint32_t gyro_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gyro_x |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    gyro_x |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gyro_x = (int32_t)gyro_x;
    gyro_y = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    gyro_y |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    gyro_y |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->gyro_y = (int32_t)gyro_y;

    return (0);
}

int rover_imu_gyro_xy_init(struct rover_imu_gyro_xy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_gyro_xy_t));

    return 0;
}

int32_t rover_imu_gyro_xy_gyro_x_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_gyro_xy_gyro_x_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_gyro_xy_gyro_x_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_gyro_xy_gyro_x_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int32_t rover_imu_gyro_xy_gyro_y_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_gyro_xy_gyro_y_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_gyro_xy_gyro_y_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_gyro_xy_gyro_y_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int rover_imu_accel_xy_pack(
    uint8_t *dst_p,
    const struct rover_imu_accel_xy_t *src_p,
    size_t size)
{
    uint32_t accel_x;
    uint32_t accel_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    accel_x = (uint32_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u32(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(accel_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(accel_x, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(accel_x, 24u, 0xffu);
    accel_y = (uint32_t)src_p->accel_y;
    dst_p[4] |= pack_left_shift_u32(accel_y, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(accel_y, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(accel_y, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(accel_y, 24u, 0xffu);

    return (8);
}

int rover_imu_accel_xy_unpack(
    struct rover_imu_accel_xy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t accel_x;
    uint32_t accel_y;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    accel_x |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    accel_x |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->accel_x = (int32_t)accel_x;
    accel_y = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    accel_y |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    accel_y |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    accel_y |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->accel_y = (int32_t)accel_y;

    return (0);
}

int rover_imu_accel_xy_init(struct rover_imu_accel_xy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_accel_xy_t));

    return 0;
}

int32_t rover_imu_accel_xy_accel_x_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_accel_xy_accel_x_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_accel_xy_accel_x_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_accel_xy_accel_x_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int32_t rover_imu_accel_xy_accel_y_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_accel_xy_accel_y_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_accel_xy_accel_y_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_accel_xy_accel_y_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int rover_imu_z_pack(
    uint8_t *dst_p,
    const struct rover_imu_z_t *src_p,
    size_t size)
{
    uint32_t accel_z;
    uint32_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gyro_z = (uint32_t)src_p->gyro_z;
    dst_p[0] |= pack_left_shift_u32(gyro_z, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gyro_z, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(gyro_z, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(gyro_z, 24u, 0xffu);
    accel_z = (uint32_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u32(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(accel_z, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(accel_z, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(accel_z, 24u, 0xffu);

    return (8);
}

int rover_imu_z_unpack(
    struct rover_imu_z_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t accel_z;
    uint32_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_z = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gyro_z |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    gyro_z |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gyro_z = (int32_t)gyro_z;
    accel_z = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    accel_z |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    accel_z |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->accel_z = (int32_t)accel_z;

    return (0);
}

int rover_imu_z_init(struct rover_imu_z_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_imu_z_t));

    return 0;
}

int32_t rover_imu_z_gyro_z_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_z_gyro_z_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_z_gyro_z_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_z_gyro_z_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int32_t rover_imu_z_accel_z_encode(double value)
{
    return (int32_t)(value);
}

double rover_imu_z_accel_z_decode(int32_t value)
{
    return ((double)value);
}

bool rover_imu_z_accel_z_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool rover_imu_z_accel_z_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
